data = [
    "Biggest ick",
    "Most attractive feature",
    "Best sport",
    "Worst sport",
    "Best place to go on holiday",
    "Worst place to go on holiday",
    "Best food",
    "Worst food",
    "Cutest animal",
    "Biggest thing you can think of",
    "Smallest thing you can think of",
    "Scariest monster",
    "Sexiest monster",
    "Most dangerous animal",
    "Most common phobia",
    "First purchase after a lottery win",
    "Classic children's drawing",
    "Most comforting thing",
    "Famous person beginning with T",
    "Household object beginning with L",
    "Animal beginning with L",
    "Plant beginning with C",
    "Greatest Brit",
    "Most villainous Brit",
    "Best genre of music",
    "Worst genre of music",
    "Idiom",
    "Favourite superhero",
    "Favourite supervillain",
    "Farm animal",
    "Country",
    "Best Fruit",
    "Best Vegetable",
    "Best vehicle",
    "Best form of transport",
    "Best room in the house",
    "Where does the magic happen",
    "Smelliest body part",
    "007 film",
    "Comedy film",
    "Rom com",
    "Taylor swift song",
    "ABBA song",
    "Magical spell",
    "Dance move",
    "Why did the chicken cross the road",
    "Board game",
    "Computer game",
    "Historical event",
    "Favourite meme",
    "Crisp flavour",
    "A sea creature",
    "Tv show",
    "Best pet",
    "Sticky food",
    "Dryfood",
    "Wet food",
    "Animal you wouldn't want as a pet",
    "Worst place to be touched",
    "Classical element",
    "Scientific element",
    "Dice roll result",
    "A famous magician",
    "Something a cowboy would own",
    "Something a witch would own",
    "A famous musician",
    "The biggest hat",
    "Sci-fi movie",
    "Classic fiction",
    "Greek myth",
    "A planet other than earth",
    "A star other than the sun",
]
